### ISSUE TITLE
how the file 'images' come out,  mnist data or citeulike?

### ISSUE THREAD

**Issue by s1162276945** [akash13singh/mxnet-for-cdl#3]
how the file 'images' come out,  mnist data or citeulike?

**Comment by sqcheng** [comment]
When I run the code with a rating matrix (100000, 10000), the code crashed, and the reported error is attached. When I use a rating matrix (10000, 10000), it works normal. This error seems caused by memeory out. How to fix such error? 

Traceback (most recent call last):
  File "cdl.py", line 89, in <module>
    num_iter, 'sgd', l_rate=0.1, decay=0.0)#,
  File "/data/CF/mxnet-for-cdl-master-kb/autoencoder.py", line 175, in finetune
    last_batch_handle='pad')
  File "/usr/lib/python2.7/site-packages/mxnet-0.10.0-py2.7.egg/mxnet/io.py", line 579, in __init__
    self.data = _init_data(data, allow_empty=False, default_name=data_name)
  File "/usr/lib/python2.7/site-packages/mxnet-0.10.0-py2.7.egg/mxnet/io.py", line 487, in _init_data
    "should be NDArray or numpy.ndarray")
TypeError: Invalid type '<type 'numpy.ndarray'>' for data, should be NDArray or numpy.ndarray
[22:57:14] /data/CF/mxnet/dmlc-core/include/dmlc/./logging.h:304: [22:57:14] /data/CF/mxnet/mshadow/mshadow/./stream_gpu-inl.h:129: Check failed: err == CUDNN_STATUS_SUCCESS (4 vs. 0) CUDNN_STATUS_INTERNAL_ERROR

**Comment by akash13singh** [comment]
The image is generated for citeulike data. The mnist data is only test/demonstrate the autoencoder.
